x=int(input("enter the value of x"))
y=int(input("enter the value of y"))
print("addition of",x,"and",y,"is",x+y,)
print("subtraction of",x,"and",y,"is",x-y,)
print("multipilication of",x,"and",y,"is",x*y,)
print("divion of ",x,"and",y,"is",x%y,)
